/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend.take.home;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;

import backend.take.home.data.Forismatic;
import backend.take.home.data.JsonBodyHandler;
import backend.take.home.parameters.QuotelyArgs;
import org.apache.commons.cli.ParseException;

public class Quotely {
    private QuotelyArgs args;
    private HttpClient client;
    private HttpRequest request;

    public Quotely(QuotelyArgs args) {
        this.args = args;
        URI uri = this.args.buildUri();

        // create a client
        this.client = HttpClient.newHttpClient();

        // create a request
        this.request = HttpRequest.newBuilder(uri)
                .header("accept", "application/json")
                .build();
    }

    public Forismatic executeRequest() throws IOException, InterruptedException {
        var response = client.send(request, new JsonBodyHandler<>(Forismatic.class));
        return response.body().get();
    }

    public static void main(String[] args)  {
        // Parse arguments and input validation
        QuotelyArgs quotelyArgs = new QuotelyArgs();

        try {
            quotelyArgs.parseArgs(args);
        } catch (ParseException e) {
            System.out.println("Could not parse arguments: " + e.getMessage());
            return;
        }

        // Create a new Quotely which will handle the request execution
        Quotely quotely = new Quotely(quotelyArgs);

        Forismatic forismaticResponse = null;
        try {
            forismaticResponse = quotely.executeRequest();
        } catch (IOException | InterruptedException e) {
            System.out.println("Encountered error while attempting to execute the request: " + e.getMessage());
            return;
        }

        forismaticResponse.print();
    }
}
