/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend.take.home;

import org.junit.Test;

public class QuotelyTest {
    @Test
    public void executeRequest() {
        // TODO: Use Mockito to mock client and request and test the executeRequest method
        // Should not be actually calling the API while running unit tests, but should execute the full method
    }

    @Test
    public void main() {
        // TODO: Full test. Mock client and request, pass in args, and ensure the output it printed out
    }
}
